import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RainbowkitProvider from "@/providers/Rainbowkit";
import { ConnectButton } from "@/components/ConnectButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Archiver",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RainbowkitProvider>
          <div className="flex flex-col gap-5 items-end p-5">
            <div className="flex w-full items-center justify-between">
              <h1 className="font-semibold text-3xl">Web Archiver</h1>
              <ConnectButton />
            </div>
            {children}
          </div>
        </RainbowkitProvider>
      </body>
    </html>
  );
}
